#!/usr/bin/env php
<?php

use Dotenv\Dotenv;
use Codinglabs\YoloAlpha\Yolo;

file_exists(__DIR__ . '/../../autoload.php')
    ? require __DIR__ . '/../../autoload.php'
    : require __DIR__ . '/vendor/autoload.php';

// path to the app root
define('BASE_PATH', $_ENV['YOLO_BASE_PATH'] ?? __DIR__ . '/../../../');

Dotenv::createImmutable(BASE_PATH)->load();

$yolo = new Yolo();
$yolo->run();
